from __future__ import annotations


UI_TEXT_ES = {
    "Not selected": "No seleccionado",
    "SELECT DUALSENSE": "SELECCIONAR DUALSENSE",
    "HAPTIC EFFECTS": "EFECTOS HAPTICOS",
    "TRIGGER EFFECTS": "EFECTOS DE GATILLOS",
    "HUD DASHBOARD": "PANEL HUD",
    "TELEMETRY": "TELEMETRIA",
    "OPTIONS": "OPCIONES",
    "SOUND TO HAPTIC": "SONIDO A HAPTICA",
    "SELECT GAME": "SELECCIONAR JUEGO",
    "SAVE": "GUARDAR",
    "SAVE *": "GUARDAR *",
    "LOAD BACKUP": "CARGAR BACKUP",
    "SELECT PRESET": "SELECCIONAR PRESET",
    "COPY PRESET": "COPIAR PRESET",
    "Select Game": "Seleccionar juego",
    "Select Preset": "Seleccionar preset",
    "Copy preset values into {preset}": "Copiar valores a {preset}",
    "Restore Original Settings": "Restaurar ajustes originales",
    "Restore original settings cancelled.": "Restauracion cancelada.",
    "Current preset values were not changed.": "Los valores del preset actual no cambiaron.",
    "Copy preset cancelled.": "Copia de preset cancelada.",
    "Copy Preset": "Copiar preset",
    "Copy this preset's settings into the current preset?\n\nCurrent preset: {current}\nCopy from: {source}": "Copiar los ajustes de este preset al preset actual?\n\nPreset actual: {current}\nCopiar desde: {source}",
    "Restore the current preset to its original built-in settings?\n\nCurrent preset: {current}": "Restaurar el preset actual a sus ajustes originales integrados?\n\nPreset actual: {current}",
    "Main UI Language": "Idioma de UI principal",
    "Tooltip Language": "Idioma de tooltips",
    "Settings saved": "Ajustes guardados",
    "UDP Input Port": "Puerto UDP de entrada",
    "Forza Data Out sends telemetry packets to this app through a UDP port. Set the same port number here and in the game telemetry settings.": "Forza Data Out envia paquetes de telemetria a esta app mediante un puerto UDP. Usa aqui el mismo numero de puerto que en los ajustes de telemetria del juego.",
    "Port": "Puerto",
    "Enter a UDP port from 1 to 65535.": "Introduce un puerto UDP entre 1 y 65535.",
    "Cancel": "Cancelar",
    "Save": "Guardar",
    "Select DualSense Audio Device": "Seleccionar dispositivo de audio DualSense",
    "Choose the DualSense audio device used for haptic output. USB is recommended. Select a device, test haptics, then save it.": "Elige el dispositivo de audio DualSense para la salida haptica. Se recomienda USB. Selecciona un dispositivo, prueba la haptica y guardalo.",
    "Current candidates": "Candidatos actuales",
    "No current DualSense candidate has been confirmed yet.": "Aun no se ha confirmado ningun candidato DualSense actual.",
    "No current DualSense candidate found.": "No se encontro ningun candidato DualSense actual.",
    "Registered device": "Dispositivo registrado",
    "No saved device": "No hay dispositivo guardado",
    "Saved history": "Historial guardado",
    "No registered device history yet.": "Aun no hay historial de dispositivos registrados.",
    "Current candidates are refreshed from Windows. Registered device is the saved output target.": "Los candidatos actuales se actualizan desde Windows. El dispositivo registrado es el destino de salida guardado.",
    "Saved device": "Dispositivo guardado",
    "Last test": "Ultima prueba",
    "Test Haptic": "Probar haptica",
    "Refresh": "Actualizar",
    "Save Device": "Guardar dispositivo",
    "Developer real-output test mode is enabled for this process.": "El modo de prueba real de salida para desarrollador esta activo en este proceso.",
    "Real Output Test": "Prueba real de salida",
    "Stop Test": "Detener prueba",
    "Sound To Haptic": "Sonido a haptica",
    "Convert a selected Windows playback stream into DualSense channels 3/4 haptics.": "Convierte una salida de audio de Windows seleccionada en haptica por los canales 3/4 del DualSense.",
    "Capture Device": "Dispositivo de captura",
    "Current playback candidates": "Candidatos de reproduccion actuales",
    "No playback candidates have been refreshed yet.": "Aun no se han actualizado candidatos de reproduccion.",
    "No playback candidates found.": "No se encontraron candidatos de reproduccion.",
    "Registered capture": "Captura registrada",
    "No saved capture device": "No hay dispositivo de captura guardado",
    "Sound haptic settings": "Ajustes de sonido haptico",
    "Master Gain": "Ganancia principal",
    "Low Volume Cut": "Corte de volumen bajo",
    "High Cut Hz": "Corte alto Hz",
    "Dynamic Boost": "Boost dinamico",
    "Sound to Haptic is off.": "Sonido a haptica esta apagado.",
    "Refresh Capture": "Actualizar captura",
    "Save Capture": "Guardar captura",
    "Start Sound Haptic": "Iniciar haptica de sonido",
    "Stop Sound Haptic": "Detener haptica de sonido",
    "Apply Settings": "Aplicar ajustes",
    "Optional sound-driven haptics can add audio texture on top of telemetry, or run as a standalone sound-to-haptic mode.": "La haptica basada en sonido puede anadir textura sobre la telemetria o funcionar como modo independiente de sonido a haptica.",
    "Haptic Effects": "Efectos Hapticos",
    "Haptic Strength": "Intensidad haptica",
    "Advanced Settings": "Ajustes avanzados",
    "Trigger Effects": "Efectos de gatillos",
    "Trigger Strength": "Intensidad de gatillos",
    "HUD Dashboard": "Panel HUD",
    "HUD Global": "HUD global",
    "HUD Units": "Unidades HUD",
    "All HUD Scale": "Escala HUD global",
    "All HUD Opacity": "Opacidad HUD global",
    "Reset Scale": "Restablecer escala",
    "Reset Opacity": "Restablecer opacidad",
    "Speed": "Velocidad",
    "Power": "Potencia",
    "Boost": "Boost",
    "RPM Style": "Estilo RPM",
    "Classic": "Clasico",
    "Modern": "Moderno",
    "Digital Bar": "Barra digital",
    "All HUD OFF": "Todo HUD OFF",
    "All HUD ON": "Todo HUD ON",
    "Standby Hide ON": "Ocultar espera ON",
    "Standby Hide OFF": "Ocultar espera OFF",
    "HUD Location Reset": "Restablecer posicion HUD",
    "Snap HUD ON": "Snap HUD ON",
    "Snap HUD OFF": "Snap HUD OFF",
    "Snap Pixel": "Pixel snap",
    "Active HUD": "HUD activos",
    "Telemetry": "Telemetria",
    "Live graph view for selected Forza telemetry fields.": "Vista de graficos en vivo para campos de telemetria Forza seleccionados.",
    "Click a graph title to choose telemetry fields for the selected game.": "Haz clic en el titulo de un grafico para elegir campos de telemetria del juego seleccionado.",
    "click name to change telemetry": "clic en el nombre para cambiar telemetria",
    "click name to choose output effect": "clic en el nombre para elegir efecto de salida",
    "Options": "Opciones",
    "Settings are grouped as compact cards for quick review and release-ready configuration.": "Los ajustes estan agrupados en tarjetas compactas para revision rapida y configuracion de lanzamiento.",
    "Window Scale": "Escala de ventana",
    "Adjust the main interface scale.": "Ajusta la escala de la interfaz principal.",
    "Changing the main UI scale requires an app restart.": "Cambiar la escala de la UI principal requiere reiniciar la app.",
    "Language": "Idioma",
    "Choose language targets separately. Tooltip KR/CN/ES are available; main UI language currently supports EN and ES.": "Elige los idiomas por separado. Los tooltips admiten KR/CN/ES; la interfaz principal admite EN y ES.",
    "Main UI": "UI principal",
    "Tooltip": "Tooltip",
    "Preset Shortcut": "Atajo de preset",
    "Use a DualSense button combination to jump to User 2, then press the same combination again to return.": "Usa una combinacion de botones del DualSense para saltar a User 2 y vuelve a pulsarla para regresar.",
    "Shortcut": "Atajo",
    "Apply": "Aplicar",
    "Example: R3+Dpad Up. The shortcut is read from the selected DualSense device.": "Ejemplo: R3+Dpad Up. El atajo se lee desde el DualSense seleccionado.",
    "Telemetry UDP Relay": "Reenvio UDP de telemetria",
    "Copies the original Forza Data Out UDP packet to another local app, HUD, or simulator device.": "Copia el paquete UDP original de Forza Data Out a otra app local, HUD o dispositivo de simulacion.",
    "Forward raw Forza telemetry packets": "Reenviar paquetes crudos de telemetria Forza",
    "Target Host": "Host destino",
    "Target Port": "Puerto destino",
    "Use a different port from the app input. Example: app listens on 8800, relay sends to 9000.": "Usa un puerto distinto al de entrada de la app. Ejemplo: la app escucha en 8800 y el reenvio envia a 9000.",
    "Telemetry relay on": "Reenvio de telemetria ON",
    "Telemetry relay off": "Reenvio de telemetria OFF",
    "DSX Output": "Salida DSX",
    "Send adaptive trigger commands over UDP. Audio export sends the selected source to the chosen playback device.": "Envia comandos de gatillos adaptativos por UDP. La exportacion de audio envia la fuente seleccionada al dispositivo elegido.",
    "DSX Trigger UDP Bridge": "Puente UDP de gatillos DSX",
    "Host": "Host",
    "Port": "Puerto",
    "Audio Export Mode": "Modo de exportacion de audio",
    "Audio Output Device Select": "Seleccionar dispositivo de salida de audio",
    "Haptic Audio Volume": "Volumen de audio haptico",
    "DSX UDP on": "DSX UDP ON",
    "DSX UDP off": "DSX UDP OFF",
    "App Version": "Version de la app",
    "Check GitHub releases for a newer public version.": "Comprueba en GitHub si hay una version publica mas reciente.",
    "Current": "Actual",
    "Check for Updates": "Buscar actualizaciones",
}


def ui_text(text: str, language: str = "EN") -> str:
    if language == "ES":
        return UI_TEXT_ES.get(text, text)
    return text


def ui_code_text(text: str, language: str = "EN", **values) -> str:
    translated = ui_text(text, language)
    return translated.format(**values) if values else translated
